name: pyleco
channels:
  - conda-forge
dependencies:
  - pyzmq  #=25.1.2  don't pin version for python<3.9
  - uuid6=2024.1.12
  - pip  # don't pin, to gain newest conda compatibility fixes
  # - pip:
    # - openrpc==8.1.0  don't pin presence for python<3.9
# Development dependencies below
  - pytest=7.2.0
  - pytest-cov=4.1.0
  - pytest-runner=6.0.0
  - setuptools_scm # don't pin, to get newest features
  - sphinx=5.3.0
  - sphinx_rtd_theme=1.2.2
